routes/web.php
<?php

Route::group(['prefix' => App\Http\Middleware\LocaleMiddleware::getLocale()], function(){

    Route::get('/', 'IndexController@index')->name('index');
    //Route::get('/index', 'IndexController@index');
    Route::get('/info', 'IndexController@info');
    Route::get('/infoconf', 'IndexController@infoconf');

    // Pay
    Route::post( '/pay', ['uses'=>'PayController@index','as'=>'pay']);
    Route::post( '/payok', ['uses'=>'PayController@payOk','as'=>'payOk']);

    // works
    Route::get('/works', 'IndexController@works');

    Route::fallback(function () { return redirect('404error');});
    Route::view('/404error', '404error');


    Auth::routes(['verify' => true]);


    Route::get('/home', 'HomeController@index')->name('home');


    Route::get('/event', ['uses'=>'EventController@index','as'=>'event']);
    Route::get('/archive', ['uses'=>'EventController@archive','as'=>'archive']);
    Route::get('/chemistry', ['uses'=>'EventController@chemistry','as'=>'chemistry']);
    Route::get('/physics', ['uses'=>'EventController@physics','as'=>'physics']);
    Route::get('/maths', ['uses'=>'EventController@maths','as'=>'maths']);
    Route::get('/biology', ['uses'=>'EventController@biology','as'=>'biology']);
    Route::get('/economics', ['uses'=>'EventController@economics','as'=>'economics']);
    Route::get('/humanities', ['uses'=>'EventController@humanities','as'=>'humanities']);

    Route::match(['get','post'],'/event/{event}', ['uses'=>'EventController@show','as'=>'eventPart']);
    Route::get('/event/{event}/{ref_id}', 'RefController@refs');
    Route::get('/json-cities', 'User\UserInfoController@cities');
    Route::get('/json-university', 'User\UserInfoController@university');
    //Route::match(['get','post'], '/events1', ['uses' => 'Admin\EventsController@store1', 'as' => 'store1']);
    Route::get('/files/chem-2019/{file}', 'EventController@download')->name('downloadArc');


    Route::group(['middleware' => ['auth'], 'prefix'  =>  'user', 'as' => 'user.', 'namespace'    =>  'User'],
        function (){
            Route::get('/', 'UserController@index');
            Route::get('/events', ['uses' => 'UserController@events', 'as' => 'userEvents']);
            Route::get('/myref', ['uses' => 'UserController@myref', 'as' => 'myref']);
            Route::resource('/addwork', 'AddWorkController');
            Route::post('/events/store', 'UserController@store')->name('events.store');
            Route::resource('/info', 'UserInfoController');
            Route::resource('/info/univer', 'UniverInfoController');
            //Route::match(['get','post'],'/event/{events}/section/{section}', 'SectionController@index');
        });


    Route::group(['middleware' => ['auth', 'verified', 'admin'], 'prefix'  =>  'admin', 'as' => 'admin.', 'namespace'    =>  'Admin'],
        function (){
            Route::get('/', 'DashboardController@index');
            Route::resource('/users', 'UsersController');
            Route::resource('/events', 'EventsController');
            Route::resource('/price', 'PriceController');
            Route::post('/events/napochtu', 'EventsController@napochtu')->name('napochtu');
            Route::post('/events/statusset', 'EventsController@statusset')->name('statusset');
            Route::get('/events/download/{id}', 'EventsController@download')->name('download');
            Route::match(['get','post'],'/events/create/{id}', 'EventsController@step');
            Route::match(['get','post'],'/events/{events}/section/{section}', 'SectionController@index')->name('section');
        });


    Route::group(['middleware' => ['auth', 'verified', 'admin', 'general'], 'prefix'  =>  'general', 'as' => 'general.', 'namespace'    =>  'General'],
        function (){
            Route::get('/', 'DashboardController@index');
            Route::get('/info', ['uses' => 'InfoController@index', 'as' => 'info']);
            Route::get('/mbusers', ['uses' => 'MBUsersController@index', 'as' => 'mbusers']);
            Route::resource('/categories', 'CategoriesController');
            Route::resource('/degrees', 'DegreeController');
            Route::resource('/positions', 'PositionController');
            Route::resource('/events', 'EventsController');
            Route::resource('/country', 'CountryController');
            Route::resource('/country/{country}/city', 'CityController');
            Route::resource('/country/{country}/city/{city}/univers', 'UniversController');
        });

});





//Переключение языков
Route::get('setlocale/{lang}', function ($lang) {

    $referer = Redirect::back()->getTargetUrl(); //URL предыдущей страницы
    $parse_url = parse_url($referer, PHP_URL_PATH); //URI предыдущей страницы

    //разбиваем на массив по разделителю
    $segments = explode('/', $parse_url);

    //Если URL (где нажали на переключение языка) содержал корректную метку языка
    if (in_array($segments[1], App\Http\Middleware\LocaleMiddleware::$languages)) {

        unset($segments[1]); //удаляем метку
    }

    //Добавляем метку языка в URL (если выбран не язык по-умолчанию)
    if ($lang != App\Http\Middleware\LocaleMiddleware::$mainLanguage){
        array_splice($segments, 1, 0, $lang);
    }

    //формируем полный URL
    $url = Request::root().implode("/", $segments);

    //если были еще GET-параметры - добавляем их
    if(parse_url($referer, PHP_URL_QUERY)){
        $url = $url.'?'. parse_url($referer, PHP_URL_QUERY);
    }
    return redirect($url); //Перенаправляем назад на ту же страницу

})->name('setlocale');

app/Http/Controllers/General/CategoriesController.php
<?php

namespace App\Http\Controllers\General;

use App\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CategoriesController extends Controller
{
     /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    //public function index()
    //{
    //    $categories = Category::all();
    //    return view('general.categories.index', ['categories'=>$categories]);
    //}

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('general.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'image' => 'required|unique:categories',
            'title_ua' => 'required|unique:categories',
            'title_ru' => 'required|unique:categories',
            'title_en' => 'required|unique:categories'
        ]);

        Category::create($request->all());
        return redirect()->route('general.info');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::find($id);

        return view('general.categories.edit', ['category'=>$category]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'image' => 'required',
            'title_ua' => 'required',
            'title_ru' => 'required',
            'title_en' => 'required'
        ]);

        $category = Category::find($id);
        $category->update($request->all());
        return redirect()->route('general.info');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Category::find($id)->delete();
        return redirect()->route('general.info');
    }
}

app/Http/Controllers/General/CityController.php
<?php

namespace App\Http\Controllers\General;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\City;
use App\Country;
use Illuminate\Validation\Rule;

class CityController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index($country)
    {
        $countries = Country::find($country);
        $cities = City::where('country_id', $country)->get();
        $i = 0;
        return view('general.country.indexCity', [
            'countries'  =>  $countries,
            'cities'  =>  $cities,
            'i'   =>  $i
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($country)
    {
        $countries = Country::find($country);
        return view('general.country.createCity', ['countries'  =>  $countries]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, $country)
    {

        $this->validate($request, [
            'title_ua' => 'required|unique:cities',
            'title_ru' => 'required|unique:cities',
            'title_en' => 'required|unique:cities'
        ]);

        City::create($request->all());
        return redirect()->route('general.city.index', [$country]);
    }

     /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($country, $id)
    {
        $countries = Country::find($country);
        $cities = City::find($id);

        return view('general.country.editCity', ['countries'=>$countries, 'cities'=>$cities]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $country, $id)
    {
        $city = City::find($id);

        $this->validate($request, [
            'title_ua' => ['required',Rule::unique('countries')->ignore($city->id)],
            'title_ru' => ['required',Rule::unique('countries')->ignore($city->id)],
            'title_en' => ['required',Rule::unique('countries')->ignore($city->id)],
        ]);

        $city->update($request->all());

        return redirect()->route('general.city.index', [$country]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($country, $id)
    {
        City::find($id)->delete();
        return redirect()->route('general.city.index', [$country]);
    }
}

app/Http/Controllers/General/CountryController.php
<?php

namespace App\Http\Controllers\General;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Country;
use Illuminate\Validation\Rule;

class CountryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $countries = Country::all();
        $i = 0;
        return view('general.country.indexCountry', [
            'countries'  =>  $countries,
            'i'   =>  $i
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('general.country.createCountry');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'title_ua' => 'required|unique:countries',
            'title_ru' => 'required|unique:countries',
            'title_en' => 'required|unique:countries'
        ]);

        Country::create($request->all());
        return redirect()->route('general.country.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $country = Country::find($id);

        return view('general.country.editCountry', ['country'=>$country]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $country = Country::find($id);

        $this->validate($request, [
            'title_ua' => ['required',Rule::unique('countries')->ignore($country->id)],
            'title_ru' => ['required',Rule::unique('countries')->ignore($country->id)],
            'title_en' => ['required',Rule::unique('countries')->ignore($country->id)],
        ]);

        $country->update($request->all());
        return redirect()->route('general.country.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Country::find($id)->delete();
        return redirect()->route('general.country.index');
    }
}

app/Http/Controllers/General/DashboardController.php
<?php

namespace App\Http\Controllers\General;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DashboardController extends Controller
{
    public function index()
    {
        return view('general.index');
    }
}

app/Http/Controllers/General/DegreeController.php
<?php

namespace App\Http\Controllers\General;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Degree;

class DegreeController extends Controller
{
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('general.degrees.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'title_ua' => 'required|unique:degrees',
            'title_ru' => 'required|unique:degrees',
            'title_en' => 'required|unique:degrees'
        ]);

        Degree::create($request->all());
        return redirect()->route('general.info');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $degrees = Degree::find($id);

        return view('general.degrees.edit', ['degrees'=>$degrees]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'title_ua' => 'required',
            'title_ru' => 'required',
            'title_en' => 'required'
        ]);

        $degrees = Degree::find($id);
        $degrees->update($request->all());
        return redirect()->route('general.info');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Degree::find($id)->delete();
        return redirect()->route('general.info');
    }
}

app/Http/Controllers/General/InfoController.php
<?php

namespace App\Http\Controllers\General;

use App\Category;
use App\Degree;
use App\Position;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class InfoController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::all();
        $degrees = Degree::all();
        $positions = Position::all();
//dd($categories, $degrees, $positions);
        return view('general.info.index', compact('categories', 'degrees', 'positions'));
    }
}

app/Http/Controllers/General/MBUsersController.php
<?php

namespace App\Http\Controllers\General;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;

class MBUsersController extends Controller
{
    public function index()
    {

        $users = DB::table('mbusers')->get();

        return view('general.users', compact('users'));
    }
}

resources/views/general/info/index.blade.php
@extends('index')

@section('content')
    <br><br><br>
    <div class="card border-primary mb-3">
        <div class="card-header"><b>Листинг данных</b></div>
        <div class="card-body text-primary">
            <div class="container-fluid">

                <section class="content">

                    <ul class="nav nav-tabs" id="myTab" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active" id="category-tab" data-toggle="tab" href="#category" role="tab" aria-controls="category" aria-selected="true">Категории</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="position-tab" data-toggle="tab" href="#position" role="tab" aria-controls="position" aria-selected="false">Должности</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="degree-tab" data-toggle="tab" href="#degree" role="tab" aria-controls="degree" aria-selected="false">Звания</a>
                        </li>
                    </ul>
                    <div class="tab-content" id="myTabContent">
                        <div class="tab-pane fade show active" id="category" role="tabpanel" aria-labelledby="category-tab"><br>
                            <div class="form-group">
                                <a href="{{ route('general.categories.create') }}" class="btn btn-success">Добавить</a>
                            </div>
                            <table id="example1" class="table table-bordered table-striped">
                                <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Image</th>
                                    <th><img src="/img/flag-ua.png" alt="" width="30 px"> Назва</th>
                                    <th><img src="/img/flag-ru.png" alt="" width="30 px"> Название</th>
                                    <th><img src="/img/flag-en.png" alt="" width="30 px"> Title</th>
                                    <th>Действия</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($categories as $category)
                                    <tr>
                                        <td>{{ $category->id }}</td>
                                        <td>{!! $category->image !!}</td>
                                        <td>{{ $category->title_ua }}</td>
                                        <td>{{ $category->title_ru }}</td>
                                        <td>{{ $category->title_en }}</td>
                                        <td>
                                            <div class="d-inline-block">
                                                <a class="btn btn-sm btn-outline-primary waves-effect" href="{{route('general.categories.edit', $category->id)}}"><i class="far fa-edit fa-2x"></i></a>
                                            </div>
                                            <div class="d-inline-block">
                                                {{ Form::open(['route'=>['general.categories.destroy', $category->id], 'method'=>'delete']) }}
                                                <button class="btn btn-sm btn-outline-danger waves-effect" onclick="return confirm('Точно удалить категорию???')" type="submit" class="delete"><i class="fas fa-times fa-2x"></i></button>
                                                {{ Form::close() }}
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                                </tfoot>
                            </table>
                        </div>

                        <div class="tab-pane fade" id="position" role="tabpanel" aria-labelledby="position-tab"><br>
                            <div class="form-group">
                                <a href="{{ route('general.positions.create') }}" class="btn btn-success">Добавить</a>
                            </div>
                            <table id="example1" class="table table-bordered table-striped">
                                <thead>
                                <tr>
                                    <th>ID</th>
                                    <th><img src="/img/flag-ua.png" alt="" width="30 px"> Назва</th>
                                    <th><img src="/img/flag-ru.png" alt="" width="30 px"> Название</th>
                                    <th><img src="/img/flag-en.png" alt="" width="30 px"> Title</th>
                                    <th>Действия</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($positions as $position)
                                    <tr>
                                        <td>{{ $position->id }}</td>
                                        <td>{{ $position->title_ua }}</td>
                                        <td>{{ $position->title_ru }}</td>
                                        <td>{{ $position->title_en }}</td>
                                        <td>
                                            <div class="d-inline-block">
                                                <a class="btn btn-sm btn-outline-primary waves-effect" href="{{route('general.positions.edit', $position->id)}}"><i class="far fa-edit fa-2x"></i></a>
                                            </div>
                                            <div class="d-inline-block">
                                                {{ Form::open(['route'=>['general.positions.destroy', $position->id], 'method'=>'delete']) }}
                                                <button class="btn btn-sm btn-outline-danger waves-effect" onclick="return confirm('Точно удалить должность???')" type="submit" class="delete"><i class="fas fa-times fa-2x"></i></button>
                                                {{ Form::close() }}
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                                </tfoot>
                            </table>
                        </div>

                        <div class="tab-pane fade" id="degree" role="tabpanel" aria-labelledby="degree-tab"><br>
                            <div class="form-group">
                                <a href="{{ route('general.degrees.create') }}" class="btn btn-success">Добавить</a>
                            </div>
                            <table id="example1" class="table table-bordered table-striped">
                                <thead>
                                <tr>
                                    <th>ID</th>
                                    <th><img src="/img/flag-ua.png" alt="" width="30 px"> Назва</th>
                                    <th><img src="/img/flag-ru.png" alt="" width="30 px"> Название</th>
                                    <th><img src="/img/flag-en.png" alt="" width="30 px"> Title</th>
                                    <th>Действия</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($degrees as $degree)
                                    <tr>
                                        <td>{{ $degree->id }}</td>
                                        <td>{{ $degree->title_ua }}</td>
                                        <td>{{ $degree->title_ru }}</td>
                                        <td>{{ $degree->title_en }}</td>
                                        <td>
                                            <div class="d-inline-block">
                                                <a class="btn btn-sm btn-outline-primary waves-effect" href="{{route('general.degrees.edit', $degree->id)}}"><i class="far fa-edit fa-2x"></i></a>
                                            </div>
                                            <div class="d-inline-block">
                                                {{ Form::open(['route'=>['general.degrees.destroy', $degree->id], 'method'=>'delete']) }}
                                                <button class="delete btn btn-sm btn-outline-danger waves-effect" onclick="return confirm('Точно удалить звание???')" type="submit" class=""><i class="fas fa-times fa-2x"></i></button>
                                                {{ Form::close() }}
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                                </tfoot>
                            </table>
                        </div>
                    </div>

                </section>

            </div>
        </div>
    </div>
@endsection