routes/web.php
<?php

Route::group(['prefix' => App\Http\Middleware\LocaleMiddleware::getLocale()], function(){

    Route::get('/', 'IndexController@index')->name('index');
    //Route::get('/index', 'IndexController@index');
    Route::get('/info', 'IndexController@info');
    Route::get('/infoconf', 'IndexController@infoconf');

    // Pay
    Route::post( '/pay', ['uses'=>'PayController@index','as'=>'pay']);
    Route::post( '/payok', ['uses'=>'PayController@payOk','as'=>'payOk']);

    // works
    Route::get('/works', 'IndexController@works');

    Route::fallback(function () { return redirect('404error');});
    Route::view('/404error', '404error');


    Auth::routes(['verify' => true]);


    Route::get('/home', 'HomeController@index')->name('home');


    Route::get('/event', ['uses'=>'EventController@index','as'=>'event']);
    Route::get('/archive', ['uses'=>'EventController@archive','as'=>'archive']);
    Route::get('/chemistry', ['uses'=>'EventController@chemistry','as'=>'chemistry']);
    Route::get('/physics', ['uses'=>'EventController@physics','as'=>'physics']);
    Route::get('/maths', ['uses'=>'EventController@maths','as'=>'maths']);
    Route::get('/biology', ['uses'=>'EventController@biology','as'=>'biology']);
    Route::get('/economics', ['uses'=>'EventController@economics','as'=>'economics']);
    Route::get('/humanities', ['uses'=>'EventController@humanities','as'=>'humanities']);

    Route::match(['get','post'],'/event/{event}', ['uses'=>'EventController@show','as'=>'eventPart']);
    Route::get('/event/{event}/{ref_id}', 'RefController@refs');
    Route::get('/json-cities', 'User\UserInfoController@cities');
    Route::get('/json-university', 'User\UserInfoController@university');
    //Route::match(['get','post'], '/events1', ['uses' => 'Admin\EventsController@store1', 'as' => 'store1']);
    Route::get('/files/chem-2019/{file}', 'EventController@download')->name('downloadArc');


    Route::group(['middleware' => ['auth'], 'prefix'  =>  'user', 'as' => 'user.', 'namespace'    =>  'User'],
        function (){
            Route::get('/', 'UserController@index');
            Route::get('/events', ['uses' => 'UserController@events', 'as' => 'userEvents']);
            Route::get('/myref', ['uses' => 'UserController@myref', 'as' => 'myref']);
            Route::resource('/addwork', 'AddWorkController');
            Route::post('/events/store', 'UserController@store')->name('events.store');
            Route::resource('/info', 'UserInfoController');
            Route::resource('/info/univer', 'UniverInfoController');
            //Route::match(['get','post'],'/event/{events}/section/{section}', 'SectionController@index');
        });


    Route::group(['middleware' => ['auth', 'verified', 'admin'], 'prefix'  =>  'admin', 'as' => 'admin.', 'namespace'    =>  'Admin'],
        function (){
            Route::get('/', 'DashboardController@index');
            Route::resource('/users', 'UsersController');
            Route::resource('/events', 'EventsController');
            Route::resource('/price', 'PriceController');
            Route::post('/events/napochtu', 'EventsController@napochtu')->name('napochtu');
            Route::post('/events/statusset', 'EventsController@statusset')->name('statusset');
            Route::get('/events/download/{id}', 'EventsController@download')->name('download');
            Route::match(['get','post'],'/events/create/{id}', 'EventsController@step');
            Route::match(['get','post'],'/events/{events}/section/{section}', 'SectionController@index')->name('section');
        });


    Route::group(['middleware' => ['auth', 'verified', 'admin', 'general'], 'prefix'  =>  'general', 'as' => 'general.', 'namespace'    =>  'General'],
        function (){
            Route::get('/', 'DashboardController@index');
            Route::get('/info', ['uses' => 'InfoController@index', 'as' => 'info']);
            Route::get('/mbusers', ['uses' => 'MBUsersController@index', 'as' => 'mbusers']);
            Route::resource('/categories', 'CategoriesController');
            Route::resource('/degrees', 'DegreeController');
            Route::resource('/positions', 'PositionController');
            Route::resource('/events', 'EventsController');
            Route::resource('/country', 'CountryController');
            Route::resource('/country/{country}/city', 'CityController');
            Route::resource('/country/{country}/city/{city}/univers', 'UniversController');
        });

});





//Переключение языков
Route::get('setlocale/{lang}', function ($lang) {

    $referer = Redirect::back()->getTargetUrl(); //URL предыдущей страницы
    $parse_url = parse_url($referer, PHP_URL_PATH); //URI предыдущей страницы

    //разбиваем на массив по разделителю
    $segments = explode('/', $parse_url);

    //Если URL (где нажали на переключение языка) содержал корректную метку языка
    if (in_array($segments[1], App\Http\Middleware\LocaleMiddleware::$languages)) {

        unset($segments[1]); //удаляем метку
    }

    //Добавляем метку языка в URL (если выбран не язык по-умолчанию)
    if ($lang != App\Http\Middleware\LocaleMiddleware::$mainLanguage){
        array_splice($segments, 1, 0, $lang);
    }

    //формируем полный URL
    $url = Request::root().implode("/", $segments);

    //если были еще GET-параметры - добавляем их
    if(parse_url($referer, PHP_URL_QUERY)){
        $url = $url.'?'. parse_url($referer, PHP_URL_QUERY);
    }
    return redirect($url); //Перенаправляем назад на ту же страницу

})->name('setlocale');

app/Country.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Country extends Model
{
    protected $fillable = ['title_ua','title_ru','title_en'];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function city()
    {
        return $this->hasMany(City::class);
    }

    public function add($fields) // Добавление страны
    {
        $country = new static;
        $country->fill($fields);
        $country->save();

        return $country;
    }

    public function edit($fields) // Изменение страны
    {
        $this->fill($fields);
        $this->save();
    }

    public function remove() // Удаление страны
    {
        $this->delete();
    }
}

app/Http/Controllers/General/CategoriesController.php
<?php

namespace App\Http\Controllers\General;

use App\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CategoriesController extends Controller
{
     /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    //public function index()
    //{
    //    $categories = Category::all();
    //    return view('general.categories.index', ['categories'=>$categories]);
    //}

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('general.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'image' => 'required|unique:categories',
            'title_ua' => 'required|unique:categories',
            'title_ru' => 'required|unique:categories',
            'title_en' => 'required|unique:categories'
        ]);

        Category::create($request->all());
        return redirect()->route('general.info');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::find($id);

        return view('general.categories.edit', ['category'=>$category]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'image' => 'required',
            'title_ua' => 'required',
            'title_ru' => 'required',
            'title_en' => 'required'
        ]);

        $category = Category::find($id);
        $category->update($request->all());
        return redirect()->route('general.info');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Category::find($id)->delete();
        return redirect()->route('general.info');
    }
}

app/Http/Controllers/General/CityController.php
<?php

namespace App\Http\Controllers\General;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\City;
use App\Country;
use Illuminate\Validation\Rule;

class CityController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index($country)
    {
        $countries = Country::find($country);
        $cities = City::where('country_id', $country)->get();
        $i = 0;
        return view('general.country.indexCity', [
            'countries'  =>  $countries,
            'cities'  =>  $cities,
            'i'   =>  $i
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($country)
    {
        $countries = Country::find($country);
        return view('general.country.createCity', ['countries'  =>  $countries]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, $country)
    {

        $this->validate($request, [
            'title_ua' => 'required|unique:cities',
            'title_ru' => 'required|unique:cities',
            'title_en' => 'required|unique:cities'
        ]);

        City::create($request->all());
        return redirect()->route('general.city.index', [$country]);
    }

     /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($country, $id)
    {
        $countries = Country::find($country);
        $cities = City::find($id);

        return view('general.country.editCity', ['countries'=>$countries, 'cities'=>$cities]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $country, $id)
    {
        $city = City::find($id);

        $this->validate($request, [
            'title_ua' => ['required',Rule::unique('countries')->ignore($city->id)],
            'title_ru' => ['required',Rule::unique('countries')->ignore($city->id)],
            'title_en' => ['required',Rule::unique('countries')->ignore($city->id)],
        ]);

        $city->update($request->all());

        return redirect()->route('general.city.index', [$country]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($country, $id)
    {
        City::find($id)->delete();
        return redirect()->route('general.city.index', [$country]);
    }
}

app/Http/Controllers/General/CountryController.php
<?php

namespace App\Http\Controllers\General;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Country;
use Illuminate\Validation\Rule;

class CountryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $countries = Country::all();
        $i = 0;
        return view('general.country.indexCountry', [
            'countries'  =>  $countries,
            'i'   =>  $i
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('general.country.createCountry');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'title_ua' => 'required|unique:countries',
            'title_ru' => 'required|unique:countries',
            'title_en' => 'required|unique:countries'
        ]);

        Country::create($request->all());
        return redirect()->route('general.country.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $country = Country::find($id);

        return view('general.country.editCountry', ['country'=>$country]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $country = Country::find($id);

        $this->validate($request, [
            'title_ua' => ['required',Rule::unique('countries')->ignore($country->id)],
            'title_ru' => ['required',Rule::unique('countries')->ignore($country->id)],
            'title_en' => ['required',Rule::unique('countries')->ignore($country->id)],
        ]);

        $country->update($request->all());
        return redirect()->route('general.country.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Country::find($id)->delete();
        return redirect()->route('general.country.index');
    }
}

app/Http/Controllers/General/DashboardController.php
<?php

namespace App\Http\Controllers\General;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DashboardController extends Controller
{
    public function index()
    {
        return view('general.index');
    }
}

app/Http/Controllers/General/DegreeController.php
<?php

namespace App\Http\Controllers\General;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Degree;

class DegreeController extends Controller
{
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('general.degrees.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'title_ua' => 'required|unique:degrees',
            'title_ru' => 'required|unique:degrees',
            'title_en' => 'required|unique:degrees'
        ]);

        Degree::create($request->all());
        return redirect()->route('general.info');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $degrees = Degree::find($id);

        return view('general.degrees.edit', ['degrees'=>$degrees]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'title_ua' => 'required',
            'title_ru' => 'required',
            'title_en' => 'required'
        ]);

        $degrees = Degree::find($id);
        $degrees->update($request->all());
        return redirect()->route('general.info');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Degree::find($id)->delete();
        return redirect()->route('general.info');
    }
}

app/Http/Controllers/General/InfoController.php
<?php

namespace App\Http\Controllers\General;

use App\Category;
use App\Degree;
use App\Position;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class InfoController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::all();
        $degrees = Degree::all();
        $positions = Position::all();
//dd($categories, $degrees, $positions);
        return view('general.info.index', compact('categories', 'degrees', 'positions'));
    }
}

app/Http/Controllers/General/MBUsersController.php
<?php

namespace App\Http\Controllers\General;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;

class MBUsersController extends Controller
{
    public function index()
    {

        $users = DB::table('mbusers')->get();

        return view('general.users', compact('users'));
    }
}

resources/views/general/country/createCity.blade.php
@extends('index')

@section('content')
    <br><br><br>
    <div class="card border-primary mb-3">
        <div class="card-header"><b>{{ $countries->title_ru }} - добавление города</b></div>
        <div class="card-body text-primary">
            <div class="container-fluid">

                <section class="content">
                    @include('_errors')
                    {!! Form::open(['route'=>['general.city.store', $countries->id]]) !!}

                    <div class="row">
                        <input type="hidden" value="{{ $countries->id }}" name="country_id">

                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="exampleInputEmail1"><img src="/img/flag-ua.png" alt="" width="30 px"> Назва</label>
                                <input type="text" class="form-control" id="exampleInputEmail1" placeholder="" value="{{ old('title_ua') }}" name="title_ua">
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="exampleInputEmail1"><img src="/img/flag-ru.png" alt="" width="30 px"> Название</label>
                                <input type="text" class="form-control" id="exampleInputEmail1" placeholder="" value="{{ old('title_ru') }}" name="title_ru">
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="exampleInputEmail1"><img src="/img/flag-en.png" alt="" width="30 px"> Title</label>
                                <input type="text" class="form-control" id="exampleInputEmail1" placeholder="" value="{{ old('title_en') }}" name="title_en">
                            </div>
                        </div>
                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer">
                        <a href="/general/country/{{ $countries->id }}/city" class="btn btn-default">Назад</a>
                        <button class="btn btn-success pull-right">Добавить</button>
                    </div>
                    <!-- /.box-footer-->
                    {!! Form::close() !!}
                </section>

            </div>
        </div>
    </div>
@endsection



@extends('index')

@section('content')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Добавить город
                <small>приятные слова..</small>
            </h1>
        </section>

        <!-- Main content -->
        <section class="content">

            <!-- Default box -->
            <div class="box">

            </div>
            <!-- /.box -->

        </section>
        <!-- /.content -->
    </div>
@endsection

resources/views/general/country/createCountry.blade.php
@extends('index')

@section('content')
    <br><br><br>
    <div class="card border-primary mb-3">
        <div class="card-header"><b>Добавление страны</b></div>
        <div class="card-body text-primary">
            <div class="container-fluid">

                <section class="content">
                    @include('_errors')
                        {!! Form::open(['route'=>'general.country.store']) !!}

                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="exampleInputEmail1"><img src="/img/flag-ua.png" alt="" width="30 px"> Назва</label>
                                    <input type="text" class="form-control" id="exampleInputEmail1" placeholder="" value="{{ old('title_ua') }}" name="title_ua">
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="exampleInputEmail1"><img src="/img/flag-ru.png" alt="" width="30 px"> Название</label>
                                    <input type="text" class="form-control" id="exampleInputEmail1" placeholder="" value="{{ old('title_ru') }}" name="title_ru">
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="exampleInputEmail1"><img src="/img/flag-en.png" alt="" width="30 px"> Title</label>
                                    <input type="text" class="form-control" id="exampleInputEmail1" placeholder="" value="{{ old('title_en') }}" name="title_en">
                                </div>
                            </div>
                        </div>
                        <!-- /.box-body -->
                        <div class="box-footer">
                            <a href="/general/country" class="btn btn-default">Назад</a>
                            <button class="btn btn-success pull-right">Добавить</button>
                        </div>
                        <!-- /.box-footer-->
                        {!! Form::close() !!}
                </section>

            </div>
        </div>
    </div>
@endsection

resources/views/general/country/createUnivers.blade.php
@extends('index')

@section('content')
    <br><br><br>
    <div class="card border-primary mb-3">
        <div class="card-header"><b>{{ $countries->title_ru }} - добавление города</b></div>
        <div class="card-body text-primary">
            <div class="container-fluid">

                <section class="content">
                    @include('_errors')
                        {!! Form::open(['route'=>['general.univers.store', $countries->id, $cities->id]]) !!}

                        <div class="row">
                            <input type="hidden" value="{{ $cities->id }}" name="cities_id">

                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="exampleInputEmail1"><img src="/img/flag-ua.png" alt="" width="30 px"> Назва</label>
                                    <input type="text" class="form-control" id="exampleInputEmail1" placeholder="" value="{{ old('title_ua') }}" name="title_ua">
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="exampleInputEmail1"><img src="/img/flag-ru.png" alt="" width="30 px"> Название</label>
                                    <input type="text" class="form-control" id="exampleInputEmail1" placeholder="" value="{{ old('title_ru') }}" name="title_ru">
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="exampleInputEmail1"><img src="/img/flag-en.png" alt="" width="30 px"> Title</label>
                                    <input type="text" class="form-control" id="exampleInputEmail1" placeholder="" value="{{ old('title_en') }}" name="title_en">
                                </div>
                            </div>

                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="exampleInputEmail1"><img src="/img/flag-ua.png" alt="" width="30 px"> Коротка назва</label>
                                    <input type="text" class="form-control" id="exampleInputEmail1" placeholder="" value="{{ old('short_title_ua') }}" name="short_title_ua">
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="exampleInputEmail1"><img src="/img/flag-ru.png" alt="" width="30 px"> Краткое название</label>
                                    <input type="text" class="form-control" id="exampleInputEmail1" placeholder="" value="{{ old('short_title_ru') }}" name="short_title_ru">
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="exampleInputEmail1"><img src="/img/flag-en.png" alt="" width="30 px"> Short title</label>
                                    <input type="text" class="form-control" id="exampleInputEmail1" placeholder="" value="{{ old('short_title_en') }}" name="short_title_en">
                                </div>
                            </div>

                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">URL</label>
                                    <input type="text" class="form-control" id="exampleInputEmail1" placeholder="" value="{{ old('url') }}" name="url">
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">E-mail</label>
                                    <input type="text" class="form-control" id="exampleInputEmail1" placeholder="" value="{{ old('email') }}" name="email">
                                </div>
                            </div>
                        </div>

                        <div class="box-footer">
                            <a href="/general/country/{{ $countries->id }}/city/{{ $cities->id }}/univers" class="btn btn-default">Назад</a>
                            <button class="btn btn-success pull-right">Добавить</button>
                        </div>
                        {!! Form::close() !!}

                </section>

            </div>
        </div>
    </div>
@endsection

resources/views/general/country/indexCountry.blade.php
@extends('index')

@section('content')
    <br><br><br>
    <div class="card border-primary mb-3">
        <div class="card-header"><b>Листинг стран</b></div>
        <div class="card-body text-primary">
            <div class="container-fluid">

                <section class="content">

                    <div class="form-group">
                        <a href="{{ route('general.country.create') }}" class="btn btn-success">Добавить</a>
                    </div>
                    <table id="dtBasicExample" class="table table-bordered table-striped">
                        <thead>
                        <tr>
                            <th>№</th>
                            <th><img src="/img/flag-ua.png" alt="" width="30 px"> Країна</th>
                            <th><img src="/img/flag-ru.png" alt="" width="30 px"> Страна</th>
                            <th><img src="/img/flag-en.png" alt="" width="30 px"> Country</th>
                            <th>Действия</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($countries as $country)
                            <tr>
                                <td>{{ ++$i }}</td>
                                <td><a href="country/{{ $country->id }}/city">{{ $country->title_ua }}</a></td>
                                <td>{{ $country->title_ru }}</td>
                                <td>{{ $country->title_en }}</td>
                                <td>
                                    <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
                                        <div class="btn-group mr-2" role="group" aria-label="Second group">
                                            <a href="{{route('general.country.edit', $country->id)}}" class="btn btn-sm btn-outline-primary waves-effect"><i class="far fa-edit fa-2x"></i></a>

                                            {{ Form::open(['route'=>['general.country.destroy', $country->id], 'method'=>'delete']) }}
                                            <button onclick="return confirm('Точно удалить страну???')" type="submit" class="delete btn btn-sm btn-outline-danger waves-effect"><i class="fas fa-times fa-2x"></i></button>
                                            {{ Form::close() }}
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                        </tfoot>
                    </table>

                </section>

            </div>
        </div>
    </div>
@endsection