routes/web.php
<?php

Route::group(['prefix' => App\Http\Middleware\LocaleMiddleware::getLocale()], function(){

    Route::get('/', 'IndexController@index')->name('index');
    //Route::get('/index', 'IndexController@index');
    Route::get('/info', 'IndexController@info');
    Route::get('/infoconf', 'IndexController@infoconf');

    // Pay
    Route::post( '/pay', ['uses'=>'PayController@index','as'=>'pay']);
    Route::post( '/payok', ['uses'=>'PayController@payOk','as'=>'payOk']);

    // works
    Route::get('/works', 'IndexController@works');

    Route::fallback(function () { return redirect('404error');});
    Route::view('/404error', '404error');


    Auth::routes(['verify' => true]);


    Route::get('/home', 'HomeController@index')->name('home');


    Route::get('/event', ['uses'=>'EventController@index','as'=>'event']);
    Route::get('/archive', ['uses'=>'EventController@archive','as'=>'archive']);
    Route::get('/chemistry', ['uses'=>'EventController@chemistry','as'=>'chemistry']);
    Route::get('/physics', ['uses'=>'EventController@physics','as'=>'physics']);
    Route::get('/maths', ['uses'=>'EventController@maths','as'=>'maths']);
    Route::get('/biology', ['uses'=>'EventController@biology','as'=>'biology']);
    Route::get('/economics', ['uses'=>'EventController@economics','as'=>'economics']);
    Route::get('/humanities', ['uses'=>'EventController@humanities','as'=>'humanities']);

    Route::match(['get','post'],'/event/{event}', ['uses'=>'EventController@show','as'=>'eventPart']);
    Route::get('/event/{event}/{ref_id}', 'RefController@refs');
    Route::get('/json-cities', 'User\UserInfoController@cities');
    Route::get('/json-university', 'User\UserInfoController@university');
    //Route::match(['get','post'], '/events1', ['uses' => 'Admin\EventsController@store1', 'as' => 'store1']);
    Route::get('/files/chem-2019/{file}', 'EventController@download')->name('downloadArc');


    Route::group(['middleware' => ['auth'], 'prefix'  =>  'user', 'as' => 'user.', 'namespace'    =>  'User'],
        function (){
            Route::get('/', 'UserController@index');
            Route::get('/events', ['uses' => 'UserController@events', 'as' => 'userEvents']);
            Route::get('/myref', ['uses' => 'UserController@myref', 'as' => 'myref']);
            Route::resource('/addwork', 'AddWorkController');
            Route::post('/events/store', 'UserController@store')->name('events.store');
            Route::resource('/info', 'UserInfoController');
            Route::resource('/info/univer', 'UniverInfoController');
            //Route::match(['get','post'],'/event/{events}/section/{section}', 'SectionController@index');
        });


    Route::group(['middleware' => ['auth', 'verified', 'admin'], 'prefix'  =>  'admin', 'as' => 'admin.', 'namespace'    =>  'Admin'],
        function (){
            Route::get('/', 'DashboardController@index');
            Route::resource('/users', 'UsersController');
            Route::resource('/events', 'EventsController');
            Route::resource('/price', 'PriceController');
            Route::post('/events/napochtu', 'EventsController@napochtu')->name('napochtu');
            Route::post('/events/statusset', 'EventsController@statusset')->name('statusset');
            Route::get('/events/download/{id}', 'EventsController@download')->name('download');
            Route::match(['get','post'],'/events/create/{id}', 'EventsController@step');
            Route::match(['get','post'],'/events/{events}/section/{section}', 'SectionController@index')->name('section');
        });


    Route::group(['middleware' => ['auth', 'verified', 'admin', 'general'], 'prefix'  =>  'general', 'as' => 'general.', 'namespace'    =>  'General'],
        function (){
            Route::get('/', 'DashboardController@index');
            Route::get('/info', ['uses' => 'InfoController@index', 'as' => 'info']);
            Route::get('/mbusers', ['uses' => 'MBUsersController@index', 'as' => 'mbusers']);
            Route::resource('/categories', 'CategoriesController');
            Route::resource('/degrees', 'DegreeController');
            Route::resource('/positions', 'PositionController');
            Route::resource('/events', 'EventsController');
            Route::resource('/country', 'CountryController');
            Route::resource('/country/{country}/city', 'CityController');
            Route::resource('/country/{country}/city/{city}/univers', 'UniversController');
        });

});





//Переключение языков
Route::get('setlocale/{lang}', function ($lang) {

    $referer = Redirect::back()->getTargetUrl(); //URL предыдущей страницы
    $parse_url = parse_url($referer, PHP_URL_PATH); //URI предыдущей страницы

    //разбиваем на массив по разделителю
    $segments = explode('/', $parse_url);

    //Если URL (где нажали на переключение языка) содержал корректную метку языка
    if (in_array($segments[1], App\Http\Middleware\LocaleMiddleware::$languages)) {

        unset($segments[1]); //удаляем метку
    }

    //Добавляем метку языка в URL (если выбран не язык по-умолчанию)
    if ($lang != App\Http\Middleware\LocaleMiddleware::$mainLanguage){
        array_splice($segments, 1, 0, $lang);
    }

    //формируем полный URL
    $url = Request::root().implode("/", $segments);

    //если были еще GET-параметры - добавляем их
    if(parse_url($referer, PHP_URL_QUERY)){
        $url = $url.'?'. parse_url($referer, PHP_URL_QUERY);
    }
    return redirect($url); //Перенаправляем назад на ту же страницу

})->name('setlocale');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable implements MustVerifyEmail
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *добавляем реф
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'ref_id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    ////////////////////////////////////////////

    public static function add($fields) // ???? добавление пользователя
    {
        $user = new static;
        $user->fill($fields);
        $user->password = bcrypt($fields['password']);
        $user->save();

        return $user;
    }

    public function edit($fields) // ???? изменение пользователя
    {
        $this->fill($fields);
        $this->password = bcrypt($fields['password']);
        $this->save();
    }



    public function info()
    {
        return $this->hasOne(UserInfo::class);
    }

    public function events()
    {
        return $this->hasMany(Event::class);
    }

    public function categories()
    {
        return $this->belongsToMany(Category::class, 'categories_users', 'user_id', 'category_id');
    }


    public function setCategory($ids)
    {
        if($ids == null) { return; }

        $this->categories()->sync($ids);
    }


}

app/Http/Controllers/Admin/UsersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\User;
use App\UserInfo;
use App\Participant;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class UsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $participants = Participant::all();
        $users = User::all();
        $infos = UserInfo::all();
//dd($infos);
        return view('admin.users.index', compact('participants', 'users', 'infos'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/User/AddWorkController.php
<?php

namespace App\Http\Controllers\User;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class AddWorkController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('user.works.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('user.works.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/User/DashboardController.php
<?php

namespace App\Http\Controllers\User;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DashboardController extends Controller
{
    //
}

app/Http/Controllers/User/SectionController.php
<?php

namespace App\Http\Controllers\user;

use App\Section;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class SectionController extends Controller
{
    public function index()
    {
        //$eventAlls = EventAll::all();
        $section = Section::where('admin_id',Auth::user()->id)->get();

        $events = Event::where('admin_id', Auth::user()->id)->get();
        //$participants = Participant::all();
dd($section);
        return view('user.index', compact('events'));
    }
}

app/Http/Controllers/User/UniverInfoController.php
<?php

namespace App\Http\Controllers\User;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\UserUnivers;

class UniverInfoController extends Controller
{
    public function index()
    {

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'country' =>  'required|max:255',
            'city' => 'required|max:255',
            'univer' => 'required|max:255',
            'website' => 'required|url|max:255',

        ]);

        UserUnivers::add($request->all());

        return redirect()->route('user.info.index');
    }
}

app/Http/Controllers/User/UserController.php
<?php

namespace App\Http\Controllers\User;

use App\Category;
use App\Event;
use App\Participant;
use App\Position;
use App\Price;
use App\UserInfo;
use App\UserUnivers;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Auth;
use App\User;
use Config;
use App\Translate;

class UserController extends Controller
{
    public function index()
    {
        $id = Auth::user()->id;
        $userInfo = UserInfo::where('user_id', $id)->first();

        if(UserInfo::where('user_id', $id)->first() == null) // Если данных о юзере нет --> направляем заполнять
        {
            return redirect()->route('user.info.create');
        }

        if( $userInfo->country_id == 999999 or $userInfo->city_id == 999999 or $userInfo->univer_id == 999999 )
        {
            if(UserUnivers::where('user_id', $id)->first() != null)
            {
                return redirect()->route('user.userEvents');
            }

            return view('/user/info/univer');
        }

        return redirect()->route('user.userEvents'); // user/info
    }

    public function myref()
    {
        $refs = User::where('ref_id', Auth::user()->id)->get();
        //$count = $refs->count('id');

        return view('user/myref', compact('refs'));
    }

    public function events()
    {

        $title = (new Translate('title'))->lang();
        $section = (new Translate('section'))->lang();
        $description = (new Translate('description'))->lang();

        if(isset(Auth::user()->info->id))
        {
            if (count(Participant::where('user_id', Auth::user()->id)->get())>0)
            {
                $eventDate = Event::where('status','!=',0)
                    ->where('date_close','>',now())
                    ->pluck('id');
                $participants = Participant::where('user_id', Auth::user()->id)
                    ->whereIn('event_id', $eventDate)
                    ->get();

                $oldEventDate = Event::where('status','!=',0)
                    ->where('date_close','<',now())
                    ->pluck('id');
                $oldParticipants = Participant::where('user_id', Auth::user()->id)
                    ->whereIn('event_id', $oldEventDate)
                    ->get();
            }
            else
            {
                $participants = [];
                $oldParticipants = [];
            }

            $categories = Auth::user()->categories()->pluck('category_id');
            foreach ($categories as $category)
            {
                $categories = Category::find($category);
                $actualeEvent = $categories->events;
                $actualeEvents[] = $actualeEvent;
            }

            $actualeEvents = collect($actualeEvents)->collapse()->unique()->where('status','!=',0)->where('date_stop','>',now())->all();

            $actualeEventsCount = count($actualeEvents);


            return view('user.events', compact('participants', 'actualeEventsCount', 'oldParticipants', 'actualeEvents', 'title', 'section', 'description'));
        }

        return redirect('user/info');
    }

    public function store(Request $request)
    {
        $this->validate($request,
        [
            'work' => 'mimes:doc,docx',
        ]);

        //$status = Config::get('statusy.status2');

        $id = $request->id;
        $path = $request->file('work')->store('works');
        $participant = Participant::find($id);
        $participant->status = 2;
        $participant->file = $path;
        $participant->save();


        return redirect('/user/events')->with('file','ok');
    }
}

resources/views/user/_activeEvents.blade.php
@if($participants != null)
    @foreach($participants->sortBy('section_id') as $participant)
        <div class="col-md-12">
            <div class="card border-{{ $participant->statPart($participant)['border'] }} mb-3">
                <div class="card-header grey lighten-4 text-uppercase text-primary h5-responsive">
                    <a href="\event\{{ $participant->event->id }}" title="Перехід на сторінку події">{{ $participant->event->$title }}</a>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-lg-2 col-md-3 text-center">
                            <a type="button" class="btn btn-floating waves-effect" data-toggle="modal" data-target="#file{{ $participant->id }}" title="{{ $participant->statPart($participant)['t'] }}">
                                <i class="far fa-file-alt fa-2x {{ $participant->statPart($participant)['s'] }}" style="color: {{ $participant->statPart($participant)['color'] }}"></i>
                            </a>

                            <!-- Modal file -->
                            @include('user._modal_file')
                            <!-- //Modal file -->

                            <a type="button" class="btn btn-floating waves-effect z-depth-1a" data-toggle="modal" data-target="#pay{{ $participant->id }}" title="{{ $participant->statPart($participant)['p'] }}">
                                <i class="fas fa-dollar-sign fa-2x {{ $participant->statPart($participant)['sPay'] }}" style="color: {{ $participant->statPart($participant)['colorPay'] }}"></i>
                            </a>

                            <!-- Modal pay -->
                            @include('user._modal_pay')
                            <!-- //Modal pay -->
                        </div>

                        <div class="col-lg-10 col-md-9">
                            <dl class="row deep-purple-text text-justify h6-responsive">
                                <dt class="col-lg-2 col-md-2 col-sm-3 text-truncate">{{ __('lang.section') }} {{-- $participant->section_id --}}</dt>
                                <dd class="col-lg-10 col-md-10 col-sm-9">{{ $participant->section->$title }}</dd>

                                <dt class="col-md-2 text-truncate">{{ __('lang.name_work') }}</dt>
                                <dd class="col-md-10">{{ $participant->name }}</dd>

                                <dt class="col-md-2 text-truncate">{{ __('lang.avtors') }}</dt>
                                <dd class="col-md-10">{{ $participant->soavtor }}</dd>

                                <dt class="col-md-2 text-truncate">{{ __('lang.form_part') }}</dt>
                                <dd class="col-md-10">{{ $participant->form->$title }}</dd>

                                <dt class="col-md-2 text-truncate">{{ __('lang.services') }}</dt>
                                <dd class="col-md-10">1 {{ __('lang.osnBook') }}
                                    @if($participant->Nbook != 0)
                                        + {{ $participant->Nbook }}
                                        @if($participant->Nbook == 1)
                                            {{ __('lang.dopBook') }}
                                        @else
                                            {{ __('lang.dopBooks') }}
                                        @endif
                                    @endif
                                    @if($participant->dopolnitelno != null)
                                        + 1 {{ __('lang.enBook') }}
                                    @endif
                                    + 1 {{ __('lang.sertificate') }}
                                </dd>
                            </dl>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    @endforeach
@else
    <div class="container-fluid">
        <div class="col alert alert-danger alert-dismissible fade show" role="alert">
            {{ __('lang.activeEventsError1') }}<br>
            {{ __('lang.activeEventsError2') }} <a href="/" class="alert-link">http:\\sciendar.com</a>
        </div>
    </div>
@endif

resources/views/user/_actualeEvents.blade.php
<table id="dtBasicExample" class="table table-striped table-bordered table-sm" cellspacing="0" width="100%" style="color: #4c00be">
    <thead>
    <tr class="text-center">
        <th>№</th>
        <th>Дата проведения</th>
        <th>Категории</th>
        <th>Назва</th>
        <th>Заклад</th>
    </tr>
    </thead>
    <tbody>
        @foreach($actualeEvents as $actualeEvent)
            <tr class="text-center">
                <td>{{ $loop->iteration }}</td>
                <td>{{ $actualeEvent->dateOnOff($actualeEvent) }}</td>
                <td>
                    @foreach($actualeEvent->categories as $category)
                        <a href="#" title="{{ $category->$title }}" style="color: rgb(76, 0, 190); font-size: 14 px"><b>{!! $category->image !!}</b></a>
                    @endforeach
                </td>
                <td class="text-left"><a href="/event/{{ $actualeEvent->id }}" class="text-primary">{{ $actualeEvent->$title }}</a></td>
                <td class="text-left">{{ $actualeEvent->univer->$title }}, {{ $actualeEvent->city->$title }}, {{ $actualeEvent->country->$title }}</td>
            </tr>
        @endforeach
    </tbody>
</table>

resources/views/user/_archiveEvents.blade.php
@if($oldParticipants != null)

    <ol>
    @foreach($oldParticipants as $oldParticipant)
        <li>
            <a href="/event/{{ $oldParticipant->event->id }}" class="text-primary">
                {{ $oldParticipant->event->dateOnOff($oldParticipant->event) }}, {{ $oldParticipant->event->description_ua }} &laquo;<span class="text-uppercase">{{ $oldParticipant->event->title_ua }}</span>&raquo;<br>
                {{ $oldParticipant->name }}<br>
                <i>{{ $oldParticipant->soavtor }}</i>
            </a>
        </li>
    @endforeach
    </ol>
@else
    <div class="alert alert-danger" role="alert">
        {{ __('lang.archiveEventsError1') }}
    </div>
@endif

resources/views/user/_modal_file.blade.php
<div class="modal fade" id="file{{ $participant->id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title deep-purple-text" id="exampleModalLabel">Стан роботи</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            @if($participant->status == 1)
                <div class="container">
                    <form class="was-validated" action="{{ route('user.events.store') }}" enctype="multipart/form-data" method="post">
                        @csrf
                        <input type="hidden" name="id" value="{{ $participant->id }}">
                        <input type="hidden" name="status" value="2">
                        <div class="modal-body deep-purple-text">
                            <br>
                            {{ __('lang.loadFile') }}
                            <img src="\img\docx_upload2.gif" alt="" width="50%">
                            <div class="custom-file">
                                <input type="file" class="custom-file-input" id="File" name="work" accept=".doc, .docx" required>
                                <label class="custom-file-label" for="File">Choose file...</label>
                                <div class="invalid-feedback">Example invalid custom file feedback</div>
                                <div class="valid-feedback">Looks good!</div>
                            </div>
                            <br>
                        </div>

                        <div class="modal-footer">
                            <input type="submit" class="btn btn-primary" name="go_work">
                        </div>
                    </form>
                </div>
            @elseif($participant->status == 2)
                <div class="modal-body text-center deep-purple-text">
                    <br>
                    Мы получили Вашу работу и уже проверяем её<br>
                    <img src="\img\icon.gif" alt="" width="50%"><br>
                    Ожидайте результата проверки<br>
                    <br>
                </div>
            @endif
        </div>
    </div>
</div>

resources/views/user/_modal_pay.blade.php
<div class="modal fade" id="pay{{ $participant->id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content deep-purple-text">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Стан оплати</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <dl class="row text-justify">
                    <dt class="col-9">{{ __('lang.uchast') }}</dt>
                    <dd class="col-3 text-right">{{ $participant->infoPay($participant)['uchastTxt'] }}</dd>

                    <dt class="col-9">{{ __('lang.dodBook') }}</dt>
                    <dd class="col-3 text-right">{{ $participant->infoPay($participant)['bookTxt'] }}</dd>

                    @if($participant->event->id != 2)
                        <dt class="col-9">{{ __('lang.engBook') }}</dt>
                        <dd class="col-3 text-right">{{ $participant->infoPay($participant)['dopTxt'] }}</dd>
                    @endif

                    <dt class="col-9"><hr></dt>
                    <dd class="col-3 text-right"><hr></dd>

                    <dt class="col-9">{{ __('lang.all') }}</dt>
                    <dd class="col-3 text-right">{{ $participant->infoPay($participant)['sumTxt'] }}</dd>
                </dl>
            </div>

                @csrf
@if($participant->pay == 2 or $participant->pay == 3)
            <div class="modal-footer">
                <div class="h2 text-uppercase text-success">
                    {{ __('lang.payOk') }} <i class="far fa-thumbs-up fa-2x"></i>
                </div>
            </div>
@else
            <div class="modal-footer">
{!! $participant->infoPay($participant)['html'] !!}
            </div>
@endif


        </div>
    </div>
</div>

resources/views/user/index.blade.php
@extends('index')

@section('content')
    <br><br><br>
    <div class="card border-primary deep-purple-text">
        <div class="card-header"><b>Персональные данные</b></div>
        <div class="card-body text-primary">
            <div class="container-fluid">
                <section class="content">

                </section>
            </div>
        </div>
    </div>
@endsection

resources/views/user/myref.blade.php
@extends('index')

@section('content')
    <br><br><br>
    <div class="card border-primary mb-3">
        <div class="card-header clearfix">
            <h1 class="text-uppercase float-left">{{ __('lang.refs') }}</h1>
        </div>
        <div class="card-body text-primary">

            <section class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col">
                            @if($refs->count('id') == 0)
                                <p>В данний час у Вас ще не має рефералів</p>
                            @else
                                <ol>
                                @foreach($refs as $ref)
                                    <li>{{ $ref->email }}</li>
                                @endforeach
                                </ol>
                            @endif
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
@endsection